### ISSUE TITLE
学習のチューニングをし隊

### ISSUE THREAD

**Issue by mynet-simai** [curiburn/learning_playground#3]
一旦特徴量は現行のでfix、いじらないことにする（本当はここもチューニングポイント）

前提：過学習してる気がする

1. ので、まず現状でsubmitして、学習データセットとのスコアを見比べる -> test: `0.76555`, train: `0.84`
2. たぶん、学習データセットのスコアより低いので、その差が埋められるなにかを考える

**Comment by curiburn** [comment]
`0.76` -> `0.7703`
🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟
